### ISSUE TITLE
when graphite_interval is not set, results in panic

### ISSUE THREAD

**Issue by Dieterbe** [graphite-ng/carbon-relay-ng#370]
```
[instrumentation]
# in addition to serving internal metrics via expvar, you can send them to graphite/carbon
# IMPORTANT: setting this to "" will disable flushing, and metrics will pile up and lead to OOM
# see https://github.com/graphite-ng/carbon-relay-ng/issues/50
# so for now you MUST send them somewhere. sorry.
# (Also, the interval here must correspond to your setting in storage-schemas.conf if you use grafana hosted metrics)
graphite_addr = "localhost:2003"
#graphite_interval = 10000  # in ms
```

results in:
```
panic: runtime error: integer divide by zero

goroutine 7 [running]:
github.com/graphite-ng/carbon-relay-ng/statsmt.tick.func1(0x0, 0xc0000a2180)
	/home/dieter/go/src/github.com/graphite-ng/carbon-relay-ng/statsmt/tick.go:12 +0x15b
created by github.com/graphite-ng/carbon-relay-ng/statsmt.tick
	/home/dieter/go/src/github.com/graphite-ng/carbon-relay-ng/statsmt/tick.go:8 +0x67
~/g/s/g/g/carbon-relay-ng ❯❯❯ vim experiments/carbon-relay-ng.ini.simple   
```

**Comment by Dieterbe** [comment]
BTW, same problem with any value under 1000
